### ISSUE TITLE
drivers.xml is missing

### ISSUE THREAD

**Issue by svenruppert** [vaadin/skeleton-starter-flow-cdi#71] opened 2019-06-27 10:30 UTC
selected from starter page, download  and after this mvn clean install will lead to 

"Failed to execute goal com.lazerycode.selenium:driver-binary-downloader-maven-plugin:1.0.17:selenium (default) on project nano-chat: Repository map '/{path to project dir}/drivers.xml' does not exist
"

**Comment by svenruppert** [comment] 2019-06-27 10:32
btw: drivers.xml is in the repo, but not included in the download.zip file

**Comment by mehdi-vaadin** [comment] 2019-07-02 21:59
The error is shown in `integration-tests` maven profile only.

**Comment by denis-anisimov** [comment] 2019-07-10 11:51
I'm not sure what to do with this....

Technically this is not an issue for this repo. Everything works fine.
The issue is only with the project downloaded from vcom: it doesn't include the file.

On the other hand we may refer to the `drivers.xml` remotely and download it if it doesn't exist....

**Comment by Legioth** [comment] 2019-07-30 07:15
How does this work for other starters?

**Comment by denis-anisimov** [comment] 2019-07-30 07:23
I'm pretty sure this is a common issue for any starter on v.com.
But this is not an issue technically for the repo itself.

v.com doesn't reproduce the repo structure. It just allows to download archived project necessary files. And archive doesn't include `drivers.xml`.

The description is not fair I think . `drivers.xml` needs to be downloaded in the `integration-tests` profile only. Which needs to be activated explicitly. 
Normally users don't need `integration-tests` profile.
But if they are going to run it then there will be an error.

**Comment by aaborschenko** [comment] 2020-02-11 17:22
It's still issue. Why not to include drivers.xml in package and close this issue?

**Comment by aaborschenko** [comment] 2020-02-11 17:48
I added manually this drivers.xml file to project root locally. But then I got another problem.
Upon integration tests execution it took me to Vaadin page saying "Your project requires Pro License". Odd


[drivers.xml.zip](https://github.com/vaadin/skeleton-starter-flow-cdi/files/4187232/drivers.xml.zip)

**Comment by Legioth** [comment] 2020-02-12 08:00
> But then I got another problem.
Upon integration tests execution it took me to Vaadin page saying "Your project requires Pro License"

The tests are using Vaadin TestBench, which is a commercial extensions that requires a Pro subscription. There is a free trial that you can use to try it out for two weeks.

**Comment by aaborschenko** [comment] 2020-02-12 12:52
I was not expecting anything NOT free to be included in my project. It’s not obvious. You could add switch to avoid such trial includes in starter. Or at least show some banner informing I have Trials included.

**Comment by anasmi** [comment] 2020-04-27 08:14
A webdriver manager is now used to configure testing https://github.com/vaadin/skeleton-starter-flow-spring/pull/303/files, so no drivers.xml file is needed anymore

Closing this ticket as obsolete. Anyway, please, comment if you disagree with the decision or you think the issue should have been addressed in another way

**Closed by anasmi** 2020-04-27 08:14 UTC
Labels: Impact: Low, Severity: Minor, bug
